//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItineraryTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItineraryTable()
        {
            this.TicketTable = new HashSet<TicketTable>();
        }
    
        public int itinerary_id { get; set; }
        public string train_number { get; set; }
        public int start_point { get; set; }
        public int end_point { get; set; }
        public int kilometres { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public string @class { get; set; }
        public decimal price_original { get; set; }
    
        public virtual TownTable TownTable { get; set; }
        public virtual TownTable TownTable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketTable> TicketTable { get; set; }
    }
}
