//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketTable()
        {
            this.UserTable = new HashSet<UserTable>();
        }
    
        public int ticket_id { get; set; }
        public string type { get; set; }
        public string direction { get; set; }
        public int price { get; set; }
        public System.DateTime date { get; set; }
        public int itinerary_id { get; set; }
    
        public virtual ItineraryTable ItineraryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTable> UserTable { get; set; }
    }
}
