//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSystemApp.Data_access_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string town { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public int ticket_id { get; set; }
    
        public virtual TicketTable TicketTable { get; set; }
    }
}
